# Generated by Django 3.1 on 2021-06-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'опубликован'), ('draft', 'черновик')], default='draft', max_length=15),
        ),
    ]
